project_id = "immqqxnblovkdvokfbef"
[functions.generate-predictions]
verify_jwt = false


[functions.verify-domain]
verify_jwt = false

[functions.cinema-chatbot]
verify_jwt = false

[functions.generate-email-content]
verify_jwt = false
